### ISSUE TITLE
Question: Is there any way to get lists without having to specify the option multiple times?

### ISSUE THREAD

**Issue by ctumolosus** [npm/nopt#27]
So instead of doing something like this:

    colorize --color blue --color red --color yellow

I would be able to do something like this:

    colorize --color blue red yellow

and get the following object as the option: `{ colorize: ['blue', 'red', 'yellow'] }`

**Comment by mklement0** [comment]
Note that to unambiguously pass your list you'd have to have to pass it as _1_ argument, such as `--color blue,red,yellow` (unquoted, but no whitespace) or `--color 'blue red yellow'` (quoted).

Looks like there's no direct support for this (as of v3.0.1).

The next best thing is to declare `--color` as `String` and then do your own splitting afterward:

```js
  parsed = nopt({ color: String }, process.argv)
  parsed.color = parsed.color.split(/ |,/);
```

However, note that you cannot combine this approach with specifying a list of permissible values; in other words: you'll have to validate the resulting array elements yourself.
