### ISSUE TITLE
Glob patterns return unexpected results

### ISSUE THREAD

**Issue by isuttell** [npm/nopt#43]
I'm trying to allow the use of glob patterns but I'm having trouble getting it to work.

````
var options = require('nopt')({
  file: String,
}, {
  'f': '--file',
}, process.argv, 2);

index.js --file www/*.js
````
`options.file` returns the first file in the directory as a string even if there are multiple files. And since it's returning a file and not the original string I can't manually glob the pattern. I've tried `file: [require('path')]` but that just resolved first path it finds.

Is there a way to turn off the path coercion or have nopt correctly recognize glob patterns and return an array of paths?

**Comment by isaacs** [comment]
No.  This is being done by the shell, not by nopt.

Observe: 

```
$ node -p process.argv *
[ '/usr/local/bin/iojs',
  'LICENSE',
  'README.md',
  'bin',
  'examples',
  'lib',
  'node_modules',
  'package.json',
  'test' ]
```
