### ISSUE TITLE
Type objects not ===

### ISSUE THREAD

**Issue by wbecker** [npm/nopt#48]
I have this weird issue where Wrapper Objects do not equate with each other. I'm running babel, and I believe that it is overriding what is normally a Number, such that the template being passed in and the internal typeDefs do not match any more.

I can fix this by changing the line [here](https://github.com/npm/nopt/blob/master/lib/nopt.js#L210) to 

```
if (t && ((type.name && t.type.name) ? (type.name === t.type.name) : (type === t.type))) {
```

This works, because the object types have a name describing them, which is a string which does a true equality test, and defaults to the old behaviour if this doesn't exist. 

The validation doesn't rely on them being the same object - is this a valid thing to do?

**Comment by tkissing** [comment]
This breaks https://github.com/daniellmb/grunt-istanbul-coverage (and probably others) in a very silent way (istanbul check-coverage is de-facto invoked with thresholds of 0, so it will always pass)

**Comment by wbecker** [comment]
Yes, that's how I spotted it too! Hopefully the PR will get accepted in the next day or so.
