### ISSUE TITLE
abbrev has no '1' version at all

### ISSUE THREAD

**Issue by marguerite** [npm/nopt#59]
Hi,

If I understand correct, according to http://semver.org/:

'abbrev':'1'

means 'abbrev':'1.0.0', not 'abbrev':'1.x', right?

but abbrev's version starts from 1.0.3.

so actually you were requiring a version that never exists.

Marguerite

**Comment by jcreamer898** [comment]
This needs to be fixed, keeps causing fails upstream for node-sass install.

**Comment by jcreamer898** [comment]
![](http://d.pr/i/1jXSI+)

**Comment by ensonic** [comment]
Can we get a release please?

**Comment by nprail** [comment]
I am experiencing this issue when using Cordova 8. `abbrev` seems to fail to install in `nopt` on both Linux and macOS. Windows seems to work fine, though. I've tried with NPM and Yarn. Both did not install it properly. 

Here's part of the build log:
```
(node:344) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module 'fs-extra'
(node:344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
module.js:540
    throw err;
    ^

Error: Cannot find module 'abbrev'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/builds/clients/IAHE-Mobile-App/node_modules/cordova/node_modules/nopt/lib/nopt.js:10:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
error Command failed with exit code 1.
```

**Comment by chinesedfan** [comment]
I met the same problem in [CarGuo/GSYGithubAPP@142a853](https://github.com/CarGuo/GSYGithubAPP/commit/142a853b2589f66054bd13711262e548221ba62a) with yarn 1.3.2. But it works in following cases (empty test repository),
- yarn add nopt
- yarn add node-pre-gyp@0.11.0
- yarn add realm@2.22.0

After upgraded to yarn@1.13.0 and rm -rf node_modules, it also works in the app repository.

**Comment by wraithgar** [comment]
fixed in https://github.com/npm/nopt/pull/89
